# -*- coding: utf-8 -*-
"""Modelo en Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4cCZaikYhgeZPpjTxHEeo7lLmuDXF0K

# Carga de Archivo
"""

# Importar las bibliotecas necesarias
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("ventas_limpias_clean-5.csv")

df["renovo"] = df["renovo"].apply(lambda x : "si" if x else "no")

"""# Preprocesamiento de Datos"""

# 1. Separar características (X) y la variable objetivo (y)
features = ['antiguedad_marca', 'participacion_mercado_promedio', 'calificacion_promedio_productos', 'numero_leads_web', 'numero_devoluciones', 'r_leads','participacion_mercado','r_roi','r_ingresoxventa','ingresos','ventas_totales']
target = 'renovo'

X = df[features]
y = df[target]

# 2. Mapear la variable objetivo a valores numéricos (si=1, no=0)
y = y.map({'si': 1, 'no': 0})

# 3. Dividir los datos en conjuntos de entrenamiento y prueba (70% entrenamiento, 30% prueba)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Tamaño del conjunto de entrenamiento (X_train): {X_train.shape}")
print(f"Tamaño del conjunto de prueba (X_test): {X_test.shape}")

"""# Evaluación del Random Forest"""

# Inicializar y entrenar el modelo Random Forest
# 'n_estimators' define la cantidad de árboles de decisión que crearán el "bosque"
rf_model = RandomForestClassifier(random_state=3002, n_estimators=100)
rf_model.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred_rf = rf_model.predict(X_test)

print("--- Métricas de Random Forest ---")
print(classification_report(y_test, y_pred_rf))

"""# Persistencia del Modelo"""

y_pred = rf_model.predict(df[features][0:3])

import joblib

# Guardar el modelo Random Forest (o el de tu elección)
filename = 'random_fores_equipo3nuevo.joblib'
joblib.dump(rf_model, filename)
print(f"Modelo '{filename}' guardado exitosamente.")